id: D37843023
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:48:43+00:00'
last_modified: '2022-05-30T06:14:57.252236+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    0933:
      image_group_id: I1PD95956
      title: སྦྱོར་བ་བརྒྱ་པ།
      total_pages: 1182
      order: 111
      base_file: 0933.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
