id: fbbe081b032f489b98916de5a507781f
initial_creation_type: ocr
source_metadata:
  volumes:
    0bbe959e63864e4fa1aa0784c68cab7e:
      base_file: v110.txt
      image_group_id: I1PD95956
      title: ''
      total_pages: 1182
      volume_number: 111
